[pytest]
testpaths = tests
python_files = test_*.py
addopts = -v --strict-markers --screenshot=only-on-failure --alluredir=allure-results
log_cli = true
log_cli_level = INFO
log_file = test_run.log
log_file_level = DEBUG
markers = 
    smoke: быстрые смоук-тесты
    mock: моки
    ui: тесты UI
    api: тесты API эндпоинтов
    regression: регрессия